# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:10.16.0

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             - v1-dependencies-

#       - run: yarn install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: yarn test


base_config: &base_config
  docker:
    - image: circleci/node:10.16.0
  working_directory: ~/project

version: 2
jobs:
  build:
    <<: *base_config
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm ci
      - run:
          name: Building in prod mode
          command: npm run prod
      - persist_to_workspace:
          root: .
          paths:
             - ./node_modules
             - ./dist
             - ./package.json
             - ./.netlify


  test:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name:  Running Tests
          command: echo "running tests"


  upload_artifacts:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: dist
          destination: dist
  
  deploy_staging:
    <<: *base_config
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Installing netlify
          command: npm -i -g install netlify
      - run:
          name: Installing netlify cli
          command: npm -i -g install netlify-cli
      - run:
          name:  Deploying to staging
          command: |
                    netlify deploy -p --dir=dist
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload_artifacts:
          requires:
            - build
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: dev